[build]
  publish = "site"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/content.json"
  [headers.values]
    Cache-Control = "no-cache"
